---
abstract: 'generate command-line dispatcher classes'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Script::Run: 0.05
configure_requires:
  ExtUtils::MakeMaker: 6.42
  File::Basename: 0
  File::ShareDir: 0
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  Perl::Tidy: 0
  Pod::Tidy: 0
  Storable: 0
  Sub::Exporter: 0
  Template: 0
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Dispatcher
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  File::Basename: 0
  File::ShareDir: 0
  File::Slurp: 0
  Getopt::Long::Descriptive: 0
  Perl::Tidy: 0
  Pod::Tidy: 0
  Storable: 0
  Sub::Exporter: 0
  Template: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: git://github.com/mlawren/app-dispatcher.git
version: 0.11
