---
abstract: 'build command-line applications with ease'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: GPL
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Dispatcher
no_index:
  directory:
    - examples
    - inc
    - share
    - t
    - xt
requires:
  File::ShareDir: 0
  Pod::Simple: 0
  Sub::Exporter: 0
  Template: 0
version: 0.01
